name: Deploy JupyterBook to GitHub Pages
on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar
  workflow_dispatch:  # Para executar o workflow manualmente
env:
  BASE_URL: /${{ github.event.repository.name }}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v5
        - name: Install uv
          uses: astral-sh/setup-uv@v6
        - name: "Set up Python"
          uses: actions/setup-python@v5
          with:
            python-version-file: ".python-version"
        - name: Install dependencies
          run: |
              uv sync --all-groups
        - name: Build documentation
          run: |
              cd tutorial/roteiro
              uv run jupyter book build --html
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: tutorial/roteiro/_build/html
