name: Deploy JupyterBook to GitHub Pages
on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar
  workflow_dispatch:  # Para executar o workflow manualmente

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v5
        - name: Install uv
          uses: astral-sh/setup-uv@v6
        - name: "Set up Python"
          uses: actions/setup-python@v5
          with:
            python-version-file: ".python-version"
        - name: Install dependencies
          run: |
              uv sync --all-groups
        - name: Build documentation
          run: |
              cd tutorial/roteiro
              make html
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: tutorial/roteiro/_build/html
